# Site settings
title: Dick Swart
tagline: "Dick Swart's personal webpage"
author:
  name: Dick Swart
  email: dick@swart.ninja
  github: https://github.com/dickswart
  linkedin: http://linkedin.com/in/dickswart
  buymeacoffee: https://www.buymeacoffee.com/swartninja
  twitter: https://twitter.com/dnswart
description: "Personal webpage of Dick Swart."

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

projects:
  sort_by: pushed # options is pushed or stars
  limit: 13
  exclude:
    archived: false
    forks: true
    projects:
      - dickswart.github.io

excerpt_separator: <!--more-->

# Timezone
timezone: Pacific/Auckland

# Permalinks
permalink: pretty
#permalink: /blog/:year/:month/:day/:title

hide_forks: true

# Sass/SCSS
sass:
  sass_dir: assets/_sass
  style: compressed # possible values: nested expanded compact compressed


